# Generated by Django 4.1.7 on 2023-03-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_modely'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modely',
            name='test_content',
        ),
        migrations.DeleteModel(
            name='ModelX',
        ),
        migrations.DeleteModel(
            name='ModelY',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
